# Generated by Django 4.2.4 on 2023-12-11 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basicapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="todo",
            new_name="todoitem",
        ),
    ]
